<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Estimate {{ $estimate->estimate_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #18181b; margin: 28px; }
        .brand { font-size: 10px; font-weight: bold; letter-spacing: 0.08em; text-transform: uppercase; color: #71717a; margin-bottom: 6px; }
        h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.02em; }
        .muted { color: #71717a; margin: 0 0 16px; }
        .meta { width: 100%; margin-top: 8px; }
        .meta td { padding: 2px 16px 2px 0; border: 0; vertical-align: top; width: 50%; }
        .meta strong { display: block; font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; color: #71717a; margin-bottom: 4px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 22px; }
        table.items th, table.items td { border: 1px solid #e4e4e7; padding: 8px; text-align: left; }
        table.items th { background: #fafafa; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; color: #52525b; }
        .right { text-align: right; }
        .totals { margin-top: 16px; width: 240px; margin-left: auto; }
        .totals td { padding: 4px 0; }
        .totals .grand { font-size: 14px; font-weight: bold; border-top: 1px solid #d4d4d8; padding-top: 8px; }
        .footer { margin-top: 28px; font-size: 10px; color: #a1a1aa; }
    </style>
</head>
<body>
    @if ($estimate->tenant?->name)
        <div class="brand">{{ $estimate->tenant->name }}</div>
    @endif
    <h1>Estimate {{ $estimate->estimate_number }}</h1>
    <p class="muted">Status: {{ ucfirst($estimate->status) }}</p>

    <table class="meta">
        <tr>
            <td>
                <strong>Prepared for</strong>
                {{ $estimate->clientAccount?->name }}
            </td>
            <td>
                <strong>Estimate date</strong>
                {{ optional($estimate->estimate_date)->format('M j, Y') ?: '—' }}<br><br>
                <strong>Valid until</strong>
                {{ optional($estimate->valid_until)->format('M j, Y') ?: '—' }}
            </td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>Description</th>
                <th class="right">Qty</th>
                <th class="right">Rate</th>
                <th class="right">Total</th>
            </tr>
        </thead>
        <tbody>
        @forelse($estimate->items as $item)
            <tr>
                <td>{{ $item->description }}</td>
                <td class="right">{{ number_format($item->quantity, 2) }}</td>
                <td class="right">{{ number_format($item->unit_price, 2) }}</td>
                <td class="right">{{ number_format($item->line_total, 2) }}</td>
            </tr>
        @empty
            <tr><td colspan="4">No line items</td></tr>
        @endforelse
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td class="muted">Subtotal</td>
            <td class="right">{{ number_format($estimate->subtotal, 2) }}</td>
        </tr>
        <tr>
            <td class="muted">Tax</td>
            <td class="right">{{ number_format($estimate->tax_total, 2) }}</td>
        </tr>
        <tr class="grand">
            <td>Grand total</td>
            <td class="right">{{ number_format($estimate->grand_total, 2) }}</td>
        </tr>
    </table>

    <div class="footer">Generated by GuardCore Pro</div>
</body>
</html>
