<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Incident #{{ $incident->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #18181b; margin: 28px; }
        .brand { font-size: 10px; font-weight: bold; letter-spacing: 0.08em; text-transform: uppercase; color: #71717a; margin-bottom: 6px; }
        h1 { font-size: 20px; margin: 0 0 12px; letter-spacing: -0.02em; }
        .meta { margin-bottom: 18px; padding: 12px; background: #fafafa; border: 1px solid #e4e4e7; }
        .meta div { margin: 0 0 6px; color: #3f3f46; }
        .meta div:last-child { margin-bottom: 0; }
        .label { display: inline-block; min-width: 72px; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.04em; color: #71717a; }
        .body { line-height: 1.5; white-space: pre-wrap; }
        .footer { margin-top: 28px; font-size: 10px; color: #a1a1aa; }
    </style>
</head>
<body>
    @if ($incident->tenant?->name ?? $incident->site?->tenant?->name ?? null)
        <div class="brand">{{ $incident->tenant?->name ?? $incident->site?->tenant?->name }}</div>
    @endif
    <h1>{{ $incident->title }}</h1>
    <div class="meta">
        <div><span class="label">Site</span> {{ $incident->site?->name ?? '—' }}</div>
        <div><span class="label">Type</span> {{ $incident->type }}</div>
        <div><span class="label">Severity</span> {{ $incident->severity }}</div>
        <div><span class="label">Status</span> {{ $incident->status }}</div>
        <div><span class="label">Reported</span> {{ optional($incident->reported_at)->format('M j, Y g:i A') ?: '—' }}</div>
    </div>
    <div class="body">{{ $incident->description }}</div>
    <div class="footer">Incident #{{ $incident->id }} · Generated by GuardCore Pro</div>
</body>
</html>
