<div class="p-6 space-y-6">
    <div><h1 class="text-2xl font-bold">Operations Dashboard</h1><p class="text-sm text-slate-500">Live command center for guards, sites, incidents, patrols, and attendance.</p></div>
    <div class="grid gap-4 md:grid-cols-6">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $stats; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label => $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <div class="rounded-xl border bg-white p-4 shadow-sm"><div class="text-xs uppercase text-slate-500"><?php echo e(str_replace('_',' ', $label)); ?></div><div class="mt-2 text-3xl font-black"><?php echo e($value); ?><?php echo e($label === 'patrol_completion' ? '%' : ''); ?></div></div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <section class="rounded-xl border bg-white p-4"><h2 class="font-bold mb-3">Latest Incidents</h2><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $incidents; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $incident): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border-t py-2"><b><?php echo e($incident->title); ?></b><div class="text-sm text-slate-500"><?php echo e($incident->site?->name); ?> · <?php echo e($incident->severity); ?> · <?php echo e($incident->status); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></section>
        <section class="rounded-xl border bg-white p-4"><h2 class="font-bold mb-3">Live Attendance</h2><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $attendance; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border-t py-2"><b><?php echo e($log->assignedGuard?->full_name ?? 'Guard'); ?></b><div class="text-sm text-slate-500"><?php echo e($log->site?->name); ?> · <?php echo e($log->status); ?> · <?php echo e($log->clock_in_at); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></section>
    </div>
</div>
<?php /**PATH /workspace/resources/views/livewire/dashboard/overview.blade.php ENDPATH**/ ?>