<?php

return [
    'default_features' => [
        'guards',
        'schedules',
        'incidents',
        'clients',
    ],

    'tiers' => [
        'starter' => [
            'label' => 'Starter',
            'features' => ['guards', 'schedules', 'attendance', 'incidents', 'patrols', 'clients'],
        ],
        'professional' => [
            'label' => 'Professional',
            'features' => ['guards', 'schedules', 'attendance', 'incidents', 'reports', 'patrols', 'gps', 'dispatch', 'clients', 'client_portal'],
        ],
        'business' => [
            'label' => 'Business',
            'features' => [
                'guards', 'schedules', 'attendance', 'incidents', 'reports', 'patrols', 'gps', 'dispatch',
                'equipment', 'visitors', 'clients', 'client_portal', 'billing', 'payroll', 'compliance',
                'analytics', 'marketplace', 'messenger', 'custom_reports', 'estimates', 'sms_alerts',
            ],
        ],
        'enterprise' => [
            'label' => 'Enterprise',
            'features' => [
                'guards', 'schedules', 'attendance', 'incidents', 'reports', 'patrols', 'gps', 'dispatch',
                'equipment', 'visitors', 'clients', 'client_portal', 'billing', 'payroll', 'compliance',
                'analytics', 'marketplace', 'messenger', 'custom_reports', 'estimates', 'sms_alerts',
                'workforce', 'passdown', 'webhooks', 'api',
            ],
        ],
    ],

    'features' => [
        'guards' => ['label' => 'Guard management', 'group' => 'Core'],
        'schedules' => ['label' => 'Scheduling & rostering', 'group' => 'Core'],
        'attendance' => ['label' => 'Attendance & timekeeping', 'group' => 'Core'],
        'incidents' => ['label' => 'Incident reporting', 'group' => 'Core'],
        'reports' => ['label' => 'Daily reports', 'group' => 'Core'],
        'patrols' => ['label' => 'Patrol routes & checkpoints', 'group' => 'Field'],
        'gps' => ['label' => 'GPS tracking & playback', 'group' => 'Field'],
        'dispatch' => ['label' => 'Dispatch control room', 'group' => 'Field'],
        'equipment' => ['label' => 'Assets management', 'group' => 'Assets'],
        'visitors' => ['label' => 'Visitor logs', 'group' => 'People'],
        'clients' => ['label' => 'Clients & sites', 'group' => 'Clients'],
        'client_portal' => ['label' => 'Client portal', 'group' => 'Clients'],
        'billing' => ['label' => 'Billing & invoices', 'group' => 'Finance'],
        'payroll' => ['label' => 'Payroll', 'group' => 'Finance'],
        'estimates' => ['label' => 'Estimates & invoicer', 'group' => 'Finance'],
        'compliance' => ['label' => 'Compliance module', 'group' => 'Compliance'],
        'analytics' => ['label' => 'Analytics dashboard', 'group' => 'Insights'],
        'marketplace' => ['label' => 'Shift marketplace', 'group' => 'Insights'],
        'custom_reports' => ['label' => 'Custom report builder', 'group' => 'Insights'],
        'messenger' => ['label' => 'Team messenger', 'group' => 'Communication'],
        'passdown' => ['label' => 'Passdown logs', 'group' => 'Communication'],
        'workforce' => ['label' => 'Shift templates & availability', 'group' => 'Workforce'],
        'sms_alerts' => ['label' => 'SMS alerts', 'group' => 'Notifications'],
        'webhooks' => ['label' => 'Outbound webhooks', 'group' => 'Enterprise'],
        'api' => ['label' => 'Enterprise API', 'group' => 'Enterprise'],
    ],

    'routes' => [
        'dispatch.control-room' => 'dispatch',
        'tracking.live' => 'gps',
        'schedules.index' => 'schedules',
        'schedules.calendar' => 'schedules',
        'schedules.deployment-sheet' => 'schedules',
        'schedules.templates' => 'schedules',
        'schedules.attendance' => 'attendance',
        'schedules.shift-status' => 'schedules',
        'schedules.open-shifts' => 'marketplace',
        'schedules.shift-exchange' => 'marketplace',
        'schedules.time-off' => 'workforce',
        'attendance.reconciliation' => 'attendance',
        'patrols.index' => 'patrols',
        'patrols.playback' => 'gps',
        'patrols.vehicles' => 'patrols',
        'passdown.index' => 'passdown',
        'incidents.index' => 'incidents',
        'reports.daily' => 'reports',
        'reports.templates' => 'custom_reports',
        'guards.index' => 'guards',
        'guards.kyg' => 'guards',
        'guards.show' => 'guards',
        'guard.mobile' => 'guards',
        'equipment.index' => 'equipment',
        'assets.overview' => 'equipment',
        'assets.index' => 'equipment',
        'assets.categories' => 'equipment',
        'assets.inventory' => 'equipment',
        'assets.vendors' => 'equipment',
        'assets.purchase-orders' => 'equipment',
        'visitors.index' => 'visitors',
        'clients.index' => 'clients',
        'sites.index' => 'clients',
        'clients.complaints' => 'clients',
        'billing.invoices' => 'billing',
        'billing.estimates' => 'estimates',
        'billing.payroll' => 'payroll',
        'messenger.index' => 'messenger',
        'client-portal.dashboard' => 'client_portal',
        'client-portal.approvals' => 'client_portal',
        'compliance.dashboard' => 'compliance',
        'compliance.policies' => 'compliance',
        'sites.compliance' => 'compliance',
        'analytics.dashboard' => 'analytics',
        'settings.webhooks' => 'webhooks',
    ],
];
