<?php

return [
    'default_features' => [
        'guards',
        'schedules',
        'incidents',
        'clients',
    ],

    'features' => [
        'guards' => ['label' => 'Guard management', 'group' => 'Core'],
        'schedules' => ['label' => 'Scheduling & rostering', 'group' => 'Core'],
        'attendance' => ['label' => 'Attendance & timekeeping', 'group' => 'Core'],
        'incidents' => ['label' => 'Incident reporting', 'group' => 'Core'],
        'reports' => ['label' => 'Daily reports', 'group' => 'Core'],
        'patrols' => ['label' => 'Patrol routes & checkpoints', 'group' => 'Field'],
        'gps' => ['label' => 'GPS tracking & playback', 'group' => 'Field'],
        'dispatch' => ['label' => 'Dispatch control room', 'group' => 'Field'],
        'equipment' => ['label' => 'Equipment tracking', 'group' => 'People'],
        'visitors' => ['label' => 'Visitor logs', 'group' => 'People'],
        'clients' => ['label' => 'Clients & sites', 'group' => 'Clients'],
        'client_portal' => ['label' => 'Client portal', 'group' => 'Clients'],
        'billing' => ['label' => 'Billing & invoices', 'group' => 'Finance'],
        'payroll' => ['label' => 'Payroll', 'group' => 'Finance'],
        'compliance' => ['label' => 'Compliance module', 'group' => 'Compliance'],
        'analytics' => ['label' => 'Analytics dashboard', 'group' => 'Insights'],
        'marketplace' => ['label' => 'Shift marketplace', 'group' => 'Insights'],
    ],

    'routes' => [
        'dispatch.control-room' => 'dispatch',
        'schedules.index' => 'schedules',
        'schedules.calendar' => 'schedules',
        'schedules.deployment-sheet' => 'schedules',
        'schedules.marketplace' => 'marketplace',
        'attendance.timekeeping' => 'attendance',
        'patrols.index' => 'patrols',
        'patrols.playback' => 'gps',
        'patrols.vehicles' => 'patrols',
        'incidents.index' => 'incidents',
        'reports.daily' => 'reports',
        'guards.index' => 'guards',
        'guards.kyg' => 'guards',
        'guards.show' => 'guards',
        'guard.mobile' => 'guards',
        'equipment.index' => 'equipment',
        'visitors.index' => 'visitors',
        'clients.index' => 'clients',
        'sites.index' => 'clients',
        'clients.complaints' => 'clients',
        'billing.invoices' => 'billing',
        'billing.payroll' => 'payroll',
        'client-portal.dashboard' => 'client_portal',
        'client-portal.approvals' => 'client_portal',
        'compliance.dashboard' => 'compliance',
        'compliance.policies' => 'compliance',
        'sites.compliance' => 'compliance',
        'analytics.dashboard' => 'analytics',
    ],
];
